name: ublue-tofu-t480
description: Universal Blue Kinoite for personal use with the ThinkPad T480

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /
  - from-file: rpm-ostree.yml
  - from-file: flatpak.yml
  - from-file: systemd.yml
  - from-file: fonts.yml
  - type: signing
